#
#/****************License************************************************
# * Vocalocity OpenVXI
# * Copyright (C) 2004-2005 by Vocalocity, Inc. All Rights Reserved.
# * This program is free software; you can redistribute it and/or
# * modify it under the terms of the GNU General Public License
# * as published by the Free Software Foundation; either version 2
# * of the License, or (at your option) any later version.
# *  
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# * Vocalocity, the Vocalocity logo, and VocalOS are trademarks or 
# * registered trademarks of Vocalocity, Inc. 
# * OpenVXI is a trademark of Scansoft, Inc. and used under license 
# * by Vocalocity.
# ***********************************************************************/
#
#**********************************************************************
#
# swichar, Vocalocity character function library
# NT make file 
#
#
#**********************************************************************/

#--------------------------------
# Required Environment Variables
#--------------------------------

!ifndef SWISBSDK
!error The environment variable SWISBSDK is not defined (it should point to your baseline directory).
!endif

# By default, set PRODUCT_LIB_PREFIX to SB
!if "$(PRODUCT_LIB_PREFIX)" == ""
!message PRODUCT_LIB_PREFIX not defined. Defaulting to SB
PRODUCT_LIB_PREFIX = SB
!endif

#--------------------------------
# Project specific settings
#--------------------------------
PROJ_ROOT = ..
BUILDSUBDIRS =
PROJ_CFLAGS = \
  -I"include"
  
PUBLIC_HEADERS = \
  include\SWIstring.h \
  include\SWIutfconversions.h \
  include\SWIprintf.h \
  include\SWIchar.h

PUBLIC_SCRIPTS =

# Explicitly specify the *.def file to define exports from DLLs
EXPLICIT_DEF_FILES = 1

#--------------------------------
# Static libraries
#--------------------------------
LIBS =

#--------------------------------
# Dynamic libraries
#--------------------------------
DLLS = $(PRODUCT_LIB_PREFIX)char

$(PRODUCT_LIB_PREFIX)char_OBJS = \
  $(BUILDDIR)/SWIstring.obj \
  $(BUILDDIR)/SWIutfconversions.obj \
  $(BUILDDIR)/SWIprintf.obj \
  $(BUILDDIR)/genchar.obj \
  $(BUILDDIR)/li_string.obj \
  $(BUILDDIR)/SWIchar.res

$(PRODUCT_LIB_PREFIX)char_LIBS =
$(PRODUCT_LIB_PREFIX)char_DEF = SWIchar.def

#-------------------------------------
# Programs
#-------------------------------------
PROGS =

#--------------------------------------------
# Include the common def's and config logic
#--------------------------------------------
!include "..\make\i386-win32\make.defs"

#------------------------------------------------
# Targets
#------------------------------------------------
all : $(LIBS) $(DLLS) $(PROGS)

#---------------------------------------------
# Include some rules common to all makefiles
#---------------------------------------------

!include "..\make\i386-win32\make.rules"
