#
#/****************License************************************************
# * Vocalocity OpenVXI
# * Copyright (C) 2004-2005 by Vocalocity, Inc. All Rights Reserved.
# * This program is free software; you can redistribute it and/or
# * modify it under the terms of the GNU General Public License
# * as published by the Free Software Foundation; either version 2
# * of the License, or (at your option) any later version.
# *  
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# * Vocalocity, the Vocalocity logo, and VocalOS are trademarks or 
# * registered trademarks of Vocalocity, Inc. 
# * OpenVXI is a trademark of Scansoft, Inc. and used under license 
# * by Vocalocity.
# ***********************************************************************/
#
#**********************************************************************
#
# VXI, Vocalocity VXML interpreter library
# NT make file 
#
#
#**********************************************************************/

#--------------------------------
# Required Environment Variables
#--------------------------------

!ifndef SWISBSDK
!error The environment variable SWISBSDK is not defined (it should point to your baseline directory).
!endif

!ifndef XERCESDIR
!error The environment variable XERCESDIR is not defined.
!endif

# By default, set PRODUCT_LIB_PREFIX to SB
!if "$(PRODUCT_LIB_PREFIX)" == ""
!message PRODUCT_LIB_PREFIX not defined. Defaulting to SB
PRODUCT_LIB_PREFIX = SB
!endif

#--------------------------------
# Project specific settings
#--------------------------------

PROJ_ROOT = ..
BUILDSUBDIRS = \
  $(BUILDDIR)\progs
  
PUBLIC_HEADERS =
PUBLIC_ERROR_FILES = \
	VXIErrors.xml \
	VXIDiagnostics.xml \
	defaults.xml	

PROJ_CFLAGS = /Zm800 \
  -I "$(XERCESDIR)/src"  \
  -I "$(XERCESDIR)/src/xercesc" \
  -I "$(XERCESDIR)/include" \
  -I "$(XERCESDIR)/include/xercesc"\
	-I"log" \
	-DHAVE_XERCES \
	-DCOMPANY_DOMAIN=L\"com.vocalocity\" \
	-DMODULE_PREFIX=L\"swi:\" \
	
MYLFLAGS = \
  -libpath:"$(XERCESDIR)/lib" \
!if "$(CFG)" == "release"
!if "$(MSVC_VERSION)" == "VC6"
  -libpath:"$(XERCESDIR)/Build/Win32/VC6/Release"
!else
  -libpath:"$(XERCESDIR)/Build/Win32/VC7/Release"
!endif
!else
!if "$(MSVC_VERSION)" == "VC6"
  -libpath:"$(XERCESDIR)/Build/Win32/VC6/Debug"
!else
  -libpath:"$(XERCESDIR)/Build/Win32/VC7/Debug"
!endif
!endif
 
# Suppress using a *.def file to define exports from DLLs, use the
# SYMBOL_EXPORT_DECL definition from VXIheaderPrefix.h instead
NO_DEF_FILES = 1

#--------------------------------
# Static libraries
#--------------------------------
LIBS = 

#--------------------------------
# Dynamic libraries
#--------------------------------
DLLS = VXI

VXI_OBJS   = $(BUILDDIR)/SimpleLogger.obj \
             $(BUILDDIR)/DocumentModel.obj \
             $(BUILDDIR)/md5.obj \
             $(BUILDDIR)/DocumentStorage.obj \
             $(BUILDDIR)/DocumentConverter.obj \
             $(BUILDDIR)/DocumentParser.obj \
             $(BUILDDIR)/VXICacheStream.obj \
             $(BUILDDIR)/GrammarManager.obj \
             $(BUILDDIR)/PromptManager.obj \
             $(BUILDDIR)/PropertyList.obj \
             $(BUILDDIR)/Counters.obj \
             $(BUILDDIR)/DialogEventCounter.obj \
             $(BUILDDIR)/Scripter.obj \
             $(BUILDDIR)/AnswerParser.obj \
             $(BUILDDIR)/VXI.obj \
             $(BUILDDIR)/VXI_api.obj \
             $(BUILDDIR)/AccessControl.obj \
             $(BUILDDIR)/TokenList.obj \
             $(BUILDDIR)/VXI.res

VXI_LIBS   = $(PRODUCT_LIB_PREFIX)trd$(CFG_SUFFIX).lib \
             VXIvalue$(CFG_SUFFIX).lib \
             $(XERCES_LIB_PREFIX)xerces-c_2$(CFG_SUFFIX).lib

#-------------------------------------
# Programs
#-------------------------------------
PROGS = ValidateDoc

ValidateDoc_OBJS = \
  $(BUILDDIR)/progs/ValidateDoc.obj \
	$(BUILDDIR)/progs/ValidateDoc.res

ValidateDoc_LIBS = \
  VXI$(CFG_SUFFIX).lib \
  VXIvalue$(CFG_SUFFIX).lib \
	$(PRODUCT_LIB_PREFIX)log$(CFG_SUFFIX).lib \
  $(PRODUCT_LIB_PREFIX)inet$(CFG_SUFFIX).lib
		
#--------------------------------------------
# Include the common def's and config logic
#--------------------------------------------
!include "..\make\i386-win32\make.defs"

#------------------------------------------------
# Targets
#------------------------------------------------
all : $(LIBS) $(DLLS) $(PROGS)

#---------------------------------------------
# Include some rules common to all makefiles
#---------------------------------------------

!include "..\make\i386-win32\make.rules"

#------------------
# Inference rules
#------------------

{progs}.c{$(BUILDDIR)/progs}.obj:
        $(CC) $(CFLAGS) $<

{progs}.cpp{$(BUILDDIR)/progs}.obj:
        $(CC) $(CPPFLAGS) $<

{progs}.rc{$(BUILDDIR)/progs}.res:
        $(RC) $(RFLAGS) /r $<
