#
#/****************License************************************************
# * Vocalocity OpenVXI
# * Copyright (C) 2004-2005 by Vocalocity, Inc. All Rights Reserved.
# * This program is free software; you can redistribute it and/or
# * modify it under the terms of the GNU General Public License
# * as published by the Free Software Foundation; either version 2
# * of the License, or (at your option) any later version.
# *  
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# * Vocalocity, the Vocalocity logo, and VocalOS are trademarks or 
# * registered trademarks of Vocalocity, Inc. 
# * OpenVXI is a trademark of Scansoft, Inc. and used under license 
# * by Vocalocity.
# ***********************************************************************/
#
#**********************************************************************
#
# SBinet, Vocalocity inet library
# NT make file 
#
#
#**********************************************************************/

#--------------------------------
# Required Environment Variables
#--------------------------------

!ifndef SWISBSDK
!error The environment variable SWISBSDK is not defined (it should point to your baseline directory).
!endif

!ifndef OPENSSLDIR
!error The environment variable OPENSSLDIR is not defined.
!endif

# By default, set PRODUCT_LIB_PREFIX to SB
!if "$(PRODUCT_LIB_PREFIX)" == ""
!message PRODUCT_LIB_PREFIX not defined. Defaulting to SB
PRODUCT_LIB_PREFIX = SB
!endif

#--------------------------------
# Project specific settings
#--------------------------------
PROJ_ROOT = ..
BUILDSUBDIRS =
PUBLIC_HEADERS = \
	SBinet.h

PUBLIC_ERROR_FILES = \
	SBinetErrors.xml \
	SBinetDiagnostics.xml

PROJ_CFLAGS = \
  -I"./" -I"$(OPENSSLDIR)/inc32" \
  -I"util" \
  -DSWIUTIL_NO_DLL \
	-DCOMPANY_DOMAIN=L\"com.vocalocity\" \
	-DMODULE_PREFIX=L\"swi:\"
	
MYLFLAGS = \
!if "$(CFG)" == "debug"
  -libpath:"$(OPENSSLDIR)/out32dll"
!else
  -libpath:"$(OPENSSLDIR)/out32dll"
!endif
 
# Suppress using a *.def file to define exports from DLLs, use the
# SYMBOL_EXPORT_DECL definition from VXIheaderPrefix.h instead
NO_DEF_FILES = 1

#--------------------------------
# Static libraries
#--------------------------------
LIBS = 

#--------------------------------
# Dynamic libraries
#--------------------------------
DLLS = $(PRODUCT_LIB_PREFIX)inet

$(PRODUCT_LIB_PREFIX)inet_OBJS = \
	$(BUILDDIR)/md5.obj \
	$(BUILDDIR)/HttpUtils.obj \
	$(BUILDDIR)/SBinet.obj \
	$(BUILDDIR)/SBinetChannel.obj\
	$(BUILDDIR)/SBinetCookie.obj \
	$(BUILDDIR)/SBinetFileStream.obj \
	$(BUILDDIR)/SBinetSSLsocket.obj \
	$(BUILDDIR)/SBinetHttpCacheStream.obj \
	$(BUILDDIR)/SBinetHttpConnection.obj \
	$(BUILDDIR)/SBinetHttpStream.obj \
	$(BUILDDIR)/SBinetProxyMatcher.obj \
	$(BUILDDIR)/SBinetStoppable.obj \
	$(BUILDDIR)/SBinetStream.obj \
	$(BUILDDIR)/SBinetTimedStream.obj \
	$(BUILDDIR)/SBinetURL.obj \
	$(BUILDDIR)/SBinetUtils.obj \
	$(BUILDDIR)/SBinetValidator.obj \
	$(BUILDDIR)/util_date.obj \
	$(BUILDDIR)/SWIHashMap.obj \
	$(BUILDDIR)/SWIList.obj \
	$(BUILDDIR)/SWIipAddress.obj \
	$(BUILDDIR)/SWIsocket.obj \
	$(BUILDDIR)/SWIinputStream.obj \
	$(BUILDDIR)/SWIoutputStream.obj \
	$(BUILDDIR)/SWIdataOutputStream.obj \
	$(BUILDDIR)/SWIbufferedInputStream.obj \
	$(BUILDDIR)/SWIbufferedOutputStream.obj \
	$(BUILDDIR)/SWIfilterInputStream.obj \
	$(BUILDDIR)/SWIfilterOutputStream.obj \
	$(BUILDDIR)/SWITimeWatch.obj \
	$(BUILDDIR)/SWITimeStamp.obj \
	$(BUILDDIR)/SWIutilLogger.obj \
	$(BUILDDIR)/SBinet.res

$(PRODUCT_LIB_PREFIX)inet_LIBS = \
# SB libraries
	VXIvalue$(CFG_SUFFIX).lib \
	$(PRODUCT_LIB_PREFIX)trd$(CFG_SUFFIX).lib \
# Open SSL
	SSLeay32.lib \
	libeay32.lib \
# WinInet libraries
	wsock32.lib \
	wininet.lib \
	urlmon.lib \
# Win32 libraries
	version.lib
		
#-------------------------------------
# Programs
#-------------------------------------
PROGS =

#--------------------------------------------
# Include the common def's and config logic
#--------------------------------------------
!include "..\make\i386-win32\make.defs"

#------------------------------------------------
# Targets
#------------------------------------------------
all : $(LIBS) $(DLLS) $(PROGS)

#---------------------------------------------
# Include some rules common to all makefiles
#---------------------------------------------

!include "..\make\i386-win32\make.rules"

#---------------------
# Inference rules
#---------------------

{util}.c{$(BUILDDIR)}.obj:
        $(CC) $(CFLAGS) -c $<

{util}.cpp{$(BUILDDIR)}.obj:
        $(CC) $(CPPFLAGS) -c $<
